# Generated by Django 2.2 on 2019-07-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False, verbose_name='教练id')),
                ('coach_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('coach_phone', models.CharField(max_length=20, verbose_name='电话')),
                ('coach_email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('coach_age', models.IntegerField(verbose_name='年龄')),
                ('coach_seniority', models.IntegerField(verbose_name='教龄')),
                ('coach_ismaster', models.IntegerField(default=0, verbose_name='是否大师')),
                ('coach_redate', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='俱乐部id')),
            ],
            options={
                'verbose_name': '教练',
                'verbose_name_plural': '教练管理',
                'db_table': 'coach',
            },
        ),
    ]
