# Generated by Django 2.2 on 2019-07-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
    ]
