# Generated by Django 2.2 on 2019-07-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(blank=True, db_index=True, editable=False, max_length=11, null=True, verbose_name='图片id')),
                ('picture_address', models.CharField(max_length=11, verbose_name='图片地址')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, db_index=True, editable=False, max_length=11, null=True, verbose_name='评论ID')),
                ('comment_user_id', models.CharField(max_length=11, verbose_name='用户id')),
                ('comment_content', models.TextField(max_length=1024, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(verbose_name='评论时间')),
                ('blueprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='晒图id')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论管理',
            },
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint_id', models.CharField(blank=True, db_index=True, editable=False, max_length=11, null=True, verbose_name='晒图id')),
                ('blueprint_content', models.CharField(max_length=40, verbose_name='内容')),
                ('blueprint_picture', models.CharField(max_length=40, verbose_name='图片')),
                ('create_time', models.DateTimeField(verbose_name='发布时间')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='俱乐部id')),
            ],
            options={
                'verbose_name': '晒图',
                'verbose_name_plural': '晒图管理',
            },
        ),
    ]
