# Generated by Django 2.2 on 2019-07-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片管理'},
        ),
        migrations.AlterModelTable(
            name='blueprint',
            table='blueprint',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='picture',
            table='picture',
        ),
    ]
