# Generated by Django 2.2 on 2019-08-31 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='train_id',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='user_id',
        ),
        migrations.AddField(
            model_name='apply',
            name='activity',
            field=models.ForeignKey(blank=True, db_column='activity_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Activity', verbose_name='活动id'),
        ),
        migrations.AddField(
            model_name='apply',
            name='train',
            field=models.ForeignKey(blank=True, db_column='train_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Train', verbose_name='训练id'),
        ),
        migrations.AddField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
    ]
