# Generated by Django 2.2 on 2019-08-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20190831_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(null=True, verbose_name='活动日期'),
        ),
    ]
