# Generated by Django 2.2 on 2019-07-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程id')),
                ('course_title', models.CharField(max_length=20, verbose_name='标题')),
                ('course_intro', models.CharField(max_length=20, verbose_name='简介')),
                ('course_cover', models.CharField(max_length=30, verbose_name='封面')),
                ('course_duration', models.IntegerField(verbose_name='时长')),
                ('course_site', models.CharField(editable=False, max_length=30, verbose_name='地点')),
                ('course_type', models.CharField(max_length=30, verbose_name='类型')),
                ('course_pubdate', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='俱乐部id')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程管理',
                'db_table': 'course',
            },
        ),
    ]
