# Generated by Django 2.2 on 2019-07-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, db_index=True, editable=False, max_length=11, null=True, verbose_name='教练id')),
                ('course_title', models.CharField(max_length=20, verbose_name='标题')),
                ('course_intro', models.CharField(max_length=20, verbose_name='简介')),
                ('course_cover', models.CharField(max_length=30, verbose_name='封面')),
                ('course_site', models.CharField(editable=False, max_length=30, verbose_name='地点')),
                ('course_type', models.CharField(max_length=30, verbose_name='类型')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='俱乐部id')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程管理',
                'db_table': 'course',
            },
        ),
    ]
