# Generated by Django 2.2 on 2019-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_date',
            field=models.DateField(verbose_name='比赛日期'),
        ),
    ]
