# Generated by Django 2.2 on 2019-07-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True, verbose_name='比赛id')),
                ('contest_name', models.CharField(max_length=256, verbose_name='比赛名称')),
                ('contest_pic', models.CharField(max_length=256, verbose_name='比赛宣传图')),
                ('contest_desc', models.TextField(max_length=1024, verbose_name='比赛简介')),
                ('contest_date', models.DateTimeField(verbose_name='比赛日期')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛管理',
                'db_table': 'contest',
            },
        ),
    ]
