# Generated by Django 2.2 on 2019-07-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('attention_id', models.AutoField(primary_key=True, serialize=False, verbose_name='关注id')),
                ('club_id', models.IntegerField(verbose_name='俱乐部id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注管理',
                'db_table': 'attention',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False, verbose_name='俱乐部id')),
                ('club_name', models.CharField(max_length=20, verbose_name='标题')),
                ('club_desc', models.TextField(max_length=4096, verbose_name='简介')),
                ('hits', models.IntegerField(default=0, editable=False, verbose_name='点击量')),
                ('fans', models.IntegerField(default=0, editable=False, verbose_name='关注量')),
                ('club_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('club_email', models.EmailField(max_length=30, verbose_name='联系邮箱')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('club_head', models.IntegerField(verbose_name='俱乐部头像')),
                ('club_administrator', models.IntegerField(editable=False, verbose_name='俱乐部管理员')),
            ],
            options={
                'verbose_name': '俱乐部',
                'verbose_name_plural': '俱乐部管理',
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False, verbose_name='教练id')),
                ('coach_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('coach_phone', models.CharField(max_length=20, verbose_name='电话')),
                ('club_id', models.IntegerField(verbose_name='俱乐部id')),
                ('coach_email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('coach_age', models.IntegerField(verbose_name='年龄')),
                ('coach_seniority', models.IntegerField(verbose_name='教龄')),
                ('coach_ismaster', models.IntegerField(default=0, verbose_name='是否大师')),
                ('coach_redate', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '教练',
                'verbose_name_plural': '教练管理',
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程id')),
                ('course_title', models.CharField(max_length=20, verbose_name='标题')),
                ('course_intro', models.CharField(max_length=20, verbose_name='简介')),
                ('club_id', models.IntegerField(verbose_name='俱乐部id')),
                ('course_cover', models.CharField(max_length=30, verbose_name='封面')),
                ('course_duration', models.IntegerField(verbose_name='时长')),
                ('course_site', models.CharField(editable=False, max_length=30, verbose_name='地点')),
                ('course_type', models.CharField(max_length=30, verbose_name='类型')),
                ('course_pubdate', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程管理',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False, verbose_name='培训id')),
                ('train_title', models.CharField(max_length=10, verbose_name='培训标题')),
                ('train_address', models.CharField(max_length=40, verbose_name='培训地点')),
                ('train_date', models.DateTimeField(verbose_name='培训日期')),
                ('train_price', models.CharField(max_length=5, verbose_name='培训价格')),
                ('train_show', models.TextField(max_length=100, verbose_name='培训简介')),
                ('club_id', models.IntegerField(verbose_name='俱乐部id')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '培训',
                'verbose_name_plural': '培训管理',
                'db_table': 'train',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False, verbose_name='视频id')),
                ('video_title', models.TextField(max_length=20, verbose_name='视频标题')),
                ('video_type', models.CharField(max_length=30, verbose_name='视频类型')),
                ('video_pic', models.CharField(max_length=30, verbose_name='视频封面图')),
                ('club_id', models.IntegerField(verbose_name='俱乐部id')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频管理',
                'db_table': 'video',
            },
        ),
    ]
