# Generated by Django 2.2 on 2019-08-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20190828_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_apply',
            field=models.BooleanField(default=False, verbose_name='是否同意申请'),
        ),
    ]
