# Generated by Django 2.2 on 2019-08-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_club_is_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_head',
            field=models.IntegerField(default=1, verbose_name='俱乐部头像'),
        ),
    ]
