# Generated by Django 2.2 on 2019-08-29 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20190829_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attention',
            name='club_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Club', verbose_name='俱乐部id'),
        ),
        migrations.AlterField(
            model_name='attention',
            name='user_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
    ]
