# Generated by Django 2.2 on 2019-08-29 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0006_auto_20190829_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attention',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='attention',
            name='user_id',
        ),
        migrations.AddField(
            model_name='attention',
            name='club',
            field=models.ForeignKey(db_column='club_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Club', verbose_name='俱乐部id'),
        ),
        migrations.AddField(
            model_name='attention',
            name='user',
            field=models.ForeignKey(db_column='user_id', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
    ]
