# Generated by Django 2.2 on 2019-08-30 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0007_auto_20190829_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='coach_redate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_pubdate',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='train',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='club_id',
        ),
        migrations.AddField(
            model_name='coach',
            name='club',
            field=models.ForeignKey(db_column='club_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Club', verbose_name='俱乐部id'),
        ),
        migrations.AddField(
            model_name='course',
            name='club',
            field=models.ForeignKey(db_column='club_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Club', verbose_name='俱乐部id'),
        ),
        migrations.AddField(
            model_name='course',
            name='up_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='train',
            name='club',
            field=models.ForeignKey(db_column='club_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Club', verbose_name='俱乐部id'),
        ),
        migrations.AddField(
            model_name='video',
            name='club',
            field=models.ForeignKey(db_column='club_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Club', verbose_name='俱乐部id'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_cover',
            field=models.IntegerField(blank=True, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_pic',
            field=models.IntegerField(default=1, verbose_name='视频封面图'),
        ),
    ]
