# Generated by Django 2.2 on 2019-08-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20190830_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='up_user',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_site',
            field=models.CharField(max_length=30, verbose_name='地点'),
        ),
    ]
