# Generated by Django 2.2 on 2019-08-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20190830_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_cover',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_intro',
            field=models.CharField(max_length=500, verbose_name='简介'),
        ),
    ]
