# Generated by Django 2.2 on 2019-08-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_auto_20190831_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_date',
            field=models.DateField(verbose_name='培训日期'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_intro',
            field=models.TextField(max_length=500, verbose_name='培训简介'),
        ),
    ]
