# Generated by Django 2.2 on 2019-08-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_auto_20190831_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_price',
            field=models.IntegerField(verbose_name='培训价格'),
        ),
    ]
