# Generated by Django 2.2 on 2019-08-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_video_up_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='./static/videos/%Y/%m/%d', verbose_name='视频地址'),
        ),
    ]
