# Generated by Django 2.2 on 2019-08-22 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('comment_content', models.TextField(max_length=1024, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(verbose_name='评论时间')),
                ('blueprint_id', models.IntegerField(verbose_name='晒图id')),
                ('from_user_id', models.IntegerField(verbose_name='评论用户id')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论管理',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False, verbose_name='图片id')),
                ('url', models.ImageField(default='', upload_to='./static/images/%Y/%m/%d', verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('user', models.ForeignKey(on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片管理',
                'db_table': 'picture',
            },
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('blueprint_id', models.AutoField(primary_key=True, serialize=False, verbose_name='晒图id')),
                ('blueprint_content', models.TextField(max_length=2048, verbose_name='晒图内容')),
                ('blueprint_picture', models.CharField(max_length=256, verbose_name='晒图图片')),
                ('create_date', models.DateTimeField(verbose_name='发布时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '晒图',
                'verbose_name_plural': '晒图管理',
                'db_table': 'blueprint',
            },
        ),
    ]
