# Generated by Django 2.2 on 2019-08-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint', '0002_auto_20190822_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='user',
            new_name='user_id',
        ),
    ]
