# Generated by Django 2.2 on 2019-08-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint', '0003_auto_20190822_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='user_id',
            new_name='user',
        ),
    ]
