# Generated by Django 2.2 on 2019-08-31 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blueprint', '0004_auto_20190822_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprint',
            name='user_id',
        ),
        migrations.AddField(
            model_name='blueprint',
            name='user',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
    ]
