# Generated by Django 2.2 on 2019-07-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False, verbose_name='培训id')),
                ('train_title', models.CharField(max_length=10, verbose_name='培训标题')),
                ('train_address', models.CharField(max_length=40, verbose_name='培训地点')),
                ('train_date', models.DateTimeField(verbose_name='培训日期')),
                ('train_price', models.CharField(max_length=5, verbose_name='培训价格')),
                ('train_show', models.TextField(max_length=100, verbose_name='培训简介')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('club_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Club', verbose_name='俱乐部id')),
            ],
            options={
                'verbose_name': '培训',
                'verbose_name_plural': '培训管理',
                'db_table': 'train',
            },
        ),
    ]
