# Generated by Django 2.2 on 2019-07-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='培训标识')),
                ('train_title', models.CharField(max_length=10, verbose_name='培训标题')),
                ('train_address', models.CharField(max_length=40, verbose_name='培训地点')),
                ('train_date', models.DateTimeField(verbose_name='培训日期')),
                ('train_price', models.CharField(max_length=5, verbose_name='培训价格')),
                ('train_show', models.TextField(max_length=100, verbose_name='培训简介')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='俱乐部id')),
            ],
            options={
                'verbose_name': '培训',
                'verbose_name_plural': '培训管理',
                'db_table': 'train',
            },
        ),
    ]
