# Generated by Django 2.2 on 2019-07-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0002_auto_20190702_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True, verbose_name='用户ID')),
                ('userName', models.CharField(max_length=256, verbose_name='用户名称')),
                ('aotId', models.CharField(blank=True, editable=False, max_length=8, null=True, verbose_name='ID')),
                ('activityOrTrain', models.IntegerField(blank=True, choices=[('activity', '1'), ('train', '0')], editable=False, null=True, verbose_name='培训/活动')),
                ('aotName', models.CharField(max_length=256, verbose_name='名称')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='报名日期')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名管理',
                'db_table': 'apply',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True, verbose_name='活动ID')),
                ('activityName', models.CharField(max_length=256, verbose_name='活动名称')),
                ('activityDesc', models.TextField(max_length=1024, verbose_name='活动简介')),
                ('train_price', models.CharField(max_length=5, verbose_name='活动价格')),
                ('hits', models.IntegerField(default=0, editable=False, verbose_name='点击量')),
                ('fans', models.IntegerField(default=0, editable=False, verbose_name='报名人数')),
                ('image', models.ImageField(blank=True, db_index=True, null=True, upload_to='static/images/', verbose_name='头像')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='所属俱乐部id')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动管理',
                'db_table': 'activity',
            },
        ),
    ]
