# Generated by Django 2.2 on 2019-07-02 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='train_price',
            new_name='activityPrice',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='club_id',
        ),
    ]
