# Generated by Django 2.2 on 2019-07-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('attention_id', models.AutoField(primary_key=True, serialize=False, verbose_name='关注id')),
                ('club_id', models.IntegerField(verbose_name='俱乐部id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注管理',
                'db_table': 'attention',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False, verbose_name='俱乐部id')),
                ('club_name', models.CharField(max_length=20, verbose_name='标题')),
                ('club_desc', models.TextField(max_length=4096, verbose_name='简介')),
                ('hits', models.IntegerField(default=0, editable=False, verbose_name='点击量')),
                ('fans', models.IntegerField(default=0, editable=False, verbose_name='关注量')),
                ('club_phone', models.CharField(editable=False, max_length=11, verbose_name='联系电话')),
                ('club_email', models.EmailField(editable=False, max_length=30, verbose_name='联系邮箱')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('club_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint.Picture', verbose_name='俱乐部头像')),
            ],
            options={
                'verbose_name': '俱乐部',
                'verbose_name_plural': '俱乐部管理',
                'db_table': 'club',
            },
        ),
    ]
