# Generated by Django 2.2 on 2019-07-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='俱乐部id')),
                ('user_id', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='用户id')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注管理',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubId', models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True, verbose_name='俱乐部ID')),
                ('clubName', models.CharField(max_length=256, verbose_name='标题')),
                ('clubDesc', models.TextField(max_length=1024, verbose_name='简介')),
                ('hits', models.IntegerField(default=0, editable=False, verbose_name='点击量')),
                ('fans', models.IntegerField(default=0, editable=False, verbose_name='关注量')),
                ('image', models.ImageField(blank=True, db_index=True, null=True, upload_to='static/images/', verbose_name='头像')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '俱乐部',
                'verbose_name_plural': '俱乐部管理',
            },
        ),
    ]
