# Generated by Django 2.2 on 2019-07-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attention',
            table='attention',
        ),
        migrations.AlterModelTable(
            name='club',
            table='club',
        ),
    ]
