# Generated by Django 2.2 on 2019-07-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False, verbose_name='视频id')),
                ('video_title', models.TextField(max_length=20, verbose_name='视频标题')),
                ('video_type', models.CharField(max_length=30, verbose_name='视频类型')),
                ('video_pic', models.CharField(max_length=30, verbose_name='视频封面图')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('club_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Club', verbose_name='俱乐部id')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频管理',
                'db_table': 'video',
            },
        ),
    ]
