# Generated by Django 2.2 on 2019-07-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, db_index=True, editable=False, max_length=11, null=True, verbose_name='视频ID')),
                ('video_name', models.TextField(max_length=20, verbose_name='视频标题')),
                ('video_type', models.CharField(max_length=30, verbose_name='视频类型')),
                ('video_pic', models.CharField(max_length=30, verbose_name='视频封面图')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='俱乐部id')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频管理',
                'db_table': 'video',
            },
        ),
    ]
